---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-bareos_console
      bareos_console_directors:
        - name: bareos-dir
          address: localhost
          password: "MySuperSecretPassword"
          description: "Bareos Console credentials for local Director"
          tls_enable: true
          tls_verify_peer: false
          dir_port: 1337
          tls_ca_cert: "/home/data/testCA.pem"
          tls_cert: "/home/data/test.pem"
          tls_key: "/home/data/test.key"
          tls_allowed_cns:
            - "bareos.example.com"
            - "bareos-webui.example.com"
            - "bareos-console.example.com"
          named_console: MyTestConsole
        - name: secondary-bareos-dir
          address: localhost
          password: "MySuperSecretSecondPassword"
          description: "Secondary Bareos Console for local Director"
          tls_enable: false
          named_console: MyNonTLSConsole
